### ISSUE TITLE
Purpose of Jay struct

### ISSUE THREAD

**Issue by a2** [DanToml/Jay#7]
It seems that the [`Jay` struct](https://github.com/czechboy0/Jay/blob/89a0bd51e2dfb1261716653c56f40356bb7299fa/Sources/Jay/Jay.swift) should have static functions instead of member functions, since the member functions only create instances of `NativeParser` and `NativeTypeConverter`.

**Comment by czechboy0** [comment]
You're right.

At the moment the struct doesn't store anything, but I'm planning to attach formatting and parsing configuration (e.g. pretty printing & accepting fragments), which you'd initialize the `Jay` struct with, and then all calls to the (de)serialization function would respect that config.

Does that make sense?

**Comment by a2** [comment]
Yeah, makes sense.
